# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e434bf95f768f99e6dbcba74a79150436d48e44c209eaed8c0fde5a2dcb78f4daa835a5131dd1664fded42272e873c9b1de9daa8b7b7a5ee0400c3cb1306fbf

test:
  secret_key_base: 1cdc97763db916479a94ced9c6775f48a535be7decc40ba73347402391b17e782497c4e594015dcb9bd1cdd36469d93ba612f7d98d527f213c4ef4d5ed4192b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
